name: sync git to s3

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}/${{ secrets.AWS_S3_BUCKET }}/$GITHUB_REPOSITORY/$GITHUB_REF_NAME/$(date +'%Y-%m-%d')
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script

      run: echo Hello from Octo Organization
